### PR TITLE
Added a new unit test for DataParallel (it fails).

### PR DESCRIPTION
**Pull request by jonathantompson**
This is an actual unit test.  As far as I can tell test_DataParallel.lua doesn't actually check the gradients.

The gradInput and gradWeights are wrong I think.  @soumith and I found one bug in parallel (it was multiply updating gradients), so I wont post an issue because he's already working on it.

Also, I have a slightly slower, but actually functional version of DataParallel if anyone is interested.  It's slower because my versions does an O(n) weight update rather than a O(n logn) update.

### CODE REVIEW

**Comment by soumith** [comment]
maybe make your default tensor type as FloatTensor? to compare apples to apples...

**Comment by jonathantompson** [comment]
Well, I was thinking that the grad accumulation order will not be the same for the CPU and GPU... So I don't expect matching floating point errors.  Therefore, my thinking was to use double for the CPU because it will be at least a reasonable ground truth value.  I'm more than happy to change it though.

**Comment by soumith** [comment]
okay that sounds reasonable. thanks.

**Comment by soumith** [comment]
i've fixed more bugs in this commit: https://github.com/facebook/fbcunn/commit/968e2a6e97c896066ded891f45143591a5521c09

but your test still does not pass. looking into it.

**Comment by soumith** [comment]
YOUR TEST IS WRONG! 

Your code:
```lua
function copyTable(x)  -- Shallow copy
  local ret = {}
  for i = 1, #x do ret[i] = x[i] end
  return ret
end
```
Correct code:
```lua
function copyTable(x)  -- Shallow copy
  local ret = {}
  for k,v in pairs(x) do ret[k] = v end
  return ret
end
```

**Comment by jonathantompson** [comment]
Dam it.  I'm so sorry.  I hope I didn't waste too much of your time.

**Comment by jonathantompson** [comment]
Well at least we have a working unit test now :-)

**Pull request merged**
